### ISSUE TITLE
Bisa lihat detail di daftar kabupaten

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#101]
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/249563/184074596-2cfb0af1-9462-4c46-aaf4-06bf1c8813ec.png">

`Kabupaten Pengguna Versi Terbaru` ganti menjadi `Kabupaten Pengguna Premium Terbaru`, yaitu mencatat desa yg menggunakan versi premium terbaru (dari Github) yg bisa di versi offline atau versi online.

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/tracksid/pull/102
