### ISSUE TITLE
BUG: identitas web milik salah satu desa tidak sesuai

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/tracksid#109]
Laporan dari pak @Fahrurro .

Identitas desa mojowarno kabupaten rembang di laman pantau menjadi https://gedebegblorakab.id/ .
Seharusnya data website desa kami di pantau adalah https://mojowarno-rembang.desa.id/ .

**Comment by apidong** [comment]
bug ini sepertinya terjadi karena ada bug pada issue https://github.com/OpenSID/tracksid/issues/113
nanti di coba setelah prnya selesai di pull

**Comment by apidong** [comment]
sudah diperbaiki di https://github.com/OpenSID/tracksid/pull/129
