### ISSUE TITLE
Penambahan status penggunaan TTE dari OpenSID 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/tracksid#110]
saat ini fitur TTE adalah fitur baru dimana belum ada tracking berapa banyak desa yang menggunakan fitur ini, berhubung fitur ini menggunakan otentikasi maka bisa dimanfaatkan untuk dilakukan pengiriman data dari OpenSID ke TrackSID untuk mengetahui berpa jumlah pengguna yang mengaktifkan TTE.

Harap perhatikan, data yg dikirim tidak boleh yg bersifat sensitif, seperti URL API Kominfo.

Dan juga sebaiknya tidak menambah pemanggilan baru ke TrackSID. Cukup dengan menambah kolom data yg sudah terkirim saat ini. Jadi seharusnya sederhana saja. Tinggal menentukan indikator TTE apa yg dapat digunakan sebagai data tambahan yg dikirim ke TrackSID.

**Comment by agungsugiarto** [comment]
Mas @apidong select module TTE masih belum menggunakan select2, kemudian pr ini belum bisa digabungkan sepertinya mangambil dari bukan base branch dev?
<img width="426" alt="image" src="https://user-images.githubusercontent.com/10989147/191206312-7749382f-0eb8-4d8e-80a5-badfee0ff077.png">

**Comment by apidong** [comment]
suda diperbaiki https://github.com/OpenSID/tracksid/pull/119
