### ISSUE TITLE
Di daftar pengguna baru, jangan tampilkan URL lokal

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#112]
Di daftar pengguna baru, jangan tampilkan URL lokal. Perhatikan bahwa di OpenDK sudah ada ketentuan bagaimana cara mendeteksi URL lokal.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/249563/188311745-5781bd9a-603e-48a3-965b-818a00ae16d2.png">

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/tracksid/pull/118
