### ISSUE TITLE
Desa yg mempunyai web salah kategori sebagai offline saja

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#113]
Klik detail Desa Aktif Hanya Offline

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/249563/188312251-6353ecb3-23f9-4f50-a3ec-5bd2913a505d.png">

Perhatikan daftar desa yg ditampilkan.

1. Seharusnya langsung tampilkan filter supaya terlihat daftar apa yg ditampilkan
2. Periksa mengapa desa yg mempunyai web tidak memiliki versi online. Seharusnya setiap desa yg mempunyai web ada versi onlinenya.

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/249563/188312452-62d647d0-647b-493f-9dcb-b9ccc9deb3e3.png">

**Comment by apidong** [comment]
mungkin yang online hanya dikenal sebagai https

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/tracksid/pull/129
