### ISSUE TITLE
Pindahkan pilihan wilayah ke header

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#114]
Hapus pilihan wilayah dari menu. Pindahkan ke header. 

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/249563/188312900-883608a8-297c-48e1-9076-559d3706d75b.png">

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/tracksid/pull/121
