### ISSUE TITLE
Daftar rincian Offline dan Online dari kabupaten salah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#132]
Kasus desa premium Kab Gresik

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/195970398-2eae7f3b-41b9-4839-816b-2819ef2a4842.png">

Kabupaten Gresik Offline premium

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/195970462-2f98bd5f-2494-4404-b812-48af9f8f1ca6.png">

Kabupaten Gresik Online premium

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/195970631-223e6849-0c60-4fd2-9cf2-fdcc6fc0f1e1.png">

**Comment by eddieridwan** [comment]
Kemungkinan errornya ada di link untuk melihat rincian Offline dan Online.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/tracksid/pull/143
