### ISSUE TITLE
Ketika mengubah nama desa di daftar wilayah, pastikan jejak akses desa terkait juga ikut terubah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#133]
Lihat contoh di Kab Gresik berikut

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/195970303-5a8e84a6-a53f-47d1-a1e6-1890dd7263a0.png">

Terlihat di situ, nama desa `Manyar Sidomukti` (baris 9) telah diubah menjadi `Manyar Sido Mukti` (baris 3). 

Kedua versi masih tampil, karena data di tabel Desa tidak ikut diubah pada waktu mengubah nama desa di Wilayah Administratif.

Perbaiki supaya tidak tampil dua versi.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/tracksid/pull/142
