### ISSUE TITLE
Peta sebaran OpenSID menunjukkan nilai berbeda setiap kali direfresh

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#134]
Berikut tangkapan layar tiga kali refresh. Sebagai contoh perhatikan jumlah desa di Sumatera berubah-ubah.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/196078508-59566659-bcb6-43ac-b757-7bef511c3afb.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/196078615-11bb76aa-df53-4d98-b2bb-50753d4ab088.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/196078736-6b50d21e-9b77-4e75-85a3-9f38ad09c322.png">

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/tracksid/pull/138
