### ISSUE TITLE
Tampilkan filter pada waktu membuka detail

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#136]
Klik detail di dasbor

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/199370130-ff219652-216a-47df-a919-bf1b4451049b.png">

Saat ini filter tidak dibuka pada daftar desa yg ditampilkan, sehingga tidak terlihat filter apa yg digunakan. Perbaiki supaya filter otomotis terlihat, seperti contoh di bawah setelah menekan Lihat Detail untuk Desa Aktif Online.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/199370486-f1e15bbc-3848-4e4c-8f86-13e5834497ea.png">

**Comment by agungsugiarto** [comment]
sudah di perbaiki melalui pr https://github.com/OpenSID/tracksid/pull/144
