### ISSUE TITLE
Daftar kabupaten yang belum ada desa OpenSID salah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#137]
Buka daftar kabupaten yg belum ada desa OpenSID. Sebagai contoh, perhatikan adanya Kab Pasaman.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/199370963-000440ed-ed99-46c4-a87f-7f9be06bce6c.png">

Sedangkan di Laporan > Desa OpenSID terlihat ada desa OpenSID di Pasaman.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/199371257-9ec42dfe-30eb-4b34-b232-81dba4948a5d.png">

Sepertinya ini terjadi karena di Wilayah Administratif tertulis nama kabupaten sebagai `KAB PASAMAN`, sedangkan sepertinya pengisian identitas desa dilakukan secara manual dengan mengisi `PASAMAN`. Desa pengguna di Pasaman termasuk yg awal menggunakan sebelum adanya integrasi dengan TrackSID. 

Karena penulisan di WIlayah Administratif adalah yg tertera di Permen, maka kita anggap yg baku. Jadi salah satu solusi adalah mengkaitkan setiap desa yg tercatat di Pasaman ke desa sebenarnya di Wilayah Administratif. Setelah memperbaiki ini, pastikan bahwa pencatatan akses oleh desa di Pasaman masih berhasil terpantau dengan benar.

Periksa juga apakah masalah ini terjadi pada kabupaten lainnya. Misalnya `Kab Lahat`.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/tracksid/pull/142
