### ISSUE TITLE
Sediakan API untuk mengambil kode dan nama wilayah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#14]
Sediakan API untuk dipanggil oleh OpenSID untuk membantu memilih kode dan nama wilayah desa. Perlu analisis untuk merancang modus yg praktis. Mungkin mendukung langkah sbb:
1. OpenSID mengirim nama desa, dan 
2. TrackSID mengembalikan semua daftar wilayah berisi nama desa tersebut. 
3. Kemudian di OpenSID memilih desa yg cocok.

**Comment by afa28** [comment]
bisa kirim contoh database website tracking pak @eddieridwan di andifahruddinakas@gmail.com

**Comment by eddieridwan** [comment]
https://opensid.slack.com/archives/C019KLR0JQM/p1603016357000100

**Comment by eddieridwan** [comment]
TrackSID sudah menyediakan API berdasarkan nama desa/kec/kab/prov persis. Perlu diubah supaya bisa mencari menggunakan `like` atau kalau bisa juga berdasarkan nilai serupa (seperti spellchecker).

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui PR #17
