### ISSUE TITLE
Jumlah desa di kabupaten salah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#145]
Jumlah desa di Kab Tulang Bawang Barat seharusnya 96 (93 desa plus 3 kelurahan)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/249563/201280878-1672d369-0080-4b48-8661-b9cadb655b01.png">

**Comment by apidong** [comment]
@vickyrolanda sudah saya perbaiki database yang diproduction. silahkan cek pak

**Comment by yogiperdana** [comment]
Selain itu terdapat duplikasi desa di kabupaten terkait 
![image](https://user-images.githubusercontent.com/14155050/206336368-1ff67442-6d77-4e93-be31-fe7a07566237.png)

**Comment by yogiperdana** [comment]
Sudah diperbaiki dan diperiksa melalui pantau
