### ISSUE TITLE
tampilkan data kiriman dari opensid yang belum ditampilkan 

### ISSUE THREAD

**Issue by apidong** [OpenSID/tracksid#146]
contoh  :
- jumlah surat tercetak.
- jumlah penduduk.
- jumlah artikel.
- jumlah surat surat keluar.
- jumlah bantuan peserta
- jumlah pengguna mandiri
- jumlah pengguna 
- jumlah unsur peta
- jumlah persil
- jumlah dokumen
- jumlah keluarga (tambahkan di opensid)

**Comment by pandigresik** [comment]
untuk saat ini hanya data berikut yang disimpan : 
'kode_pos',
            'nama_desa',
            'nama_kecamatan',
            'nama_kabupaten',
            'nama_provinsi',
            'lat',
            'lng',
            'alamat_kantor',
            'ip_lokal',
            'ip_hosting',
            'versi_lokal',
            'versi_hosting',
            'tgl_rekam_lokal',
            'tgl_rekam_hosting',
            'tgl_akses_lokal',
            'tgl_akses_hosting',
            'url_lokal',
            'url_hosting',
            'opensid_valid',
            'email_desa',
            'telepon',
            'jml_surat_tte',
            'modul_tte',
jadi harus ada penambahan kolom untuk menyimpan informasi lain yang dikirim oleh opensid.
mas @vickyrolanda , mas @apidong apakah demikian ?

**Comment by pandigresik** [comment]
mas @andifahruddinakas ini perbaikannya tentang apa ?

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/184
