### ISSUE TITLE
Data desa baru tidak lengkap

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#147]
Buka daftar desa baru. Perhatikan kolom data yg ditampilkan.
Terlihat ada desa yg datanya tidak lengkap, termasuk provinsi, web, versi dll.

![telegram-cloud-photo-size-5-6325484493766505231-y](https://user-images.githubusercontent.com/249563/203185508-e292ac1d-970a-455b-8647-f11d61e49c2d.jpg)

**Comment by apidong** [comment]
@vickyrolanda sudah diperbaiki. silahkan di cek

**Comment by yogiperdana** [comment]
Sudah diperbaiki dan diperiksa di pantau
