### ISSUE TITLE
Tambahkan pengecualian domain untuk demo

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/tracksid#148]
Saat ini hanya terdaftar: 
- 'beta.opendesa.id',
- 'beta2.opensid.or.id',
- 'berputar.opendesa.id',

https://github.com/OpenSID/tracksid/blob/e6d839fb97e6ee0f0b0a4b738d35da3e30614110/config/tracksid.php#L9

**Comment by yogiperdana** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/tracksid/pull/149
