### ISSUE TITLE
Pengaturan untuk tidak tampilkan URL web desa bagi publik

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#153]
Saat ini, jika URL web desa perlu disembunyikan (mungkin karena ada dugaan disalah-gunakan), satu2nya cara adalah menutup web Pantau sama sekali, dengan memasuki mode 'maintenance'.

Supaya fitur Pantau lainnya tetap dapat digunakan, perlu diterapkan sbb:

1. sediakan pengaturan untuk tidak menampilkan URL web kepada publik
2. jika pengaturan itu aktif, sembunyikan tampilan URL web desa pada semua halaman yg dapat dilihat publik, termasuk juga di peta sebaran
3. tetap tampilkan URL web jika telah login ke Pantau

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/tracksid/pull/154
