### ISSUE TITLE
Data yang ditampilkan tidak sesuai saat detail ditampilkan pada laporan kabupaten

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/tracksid#168]
mas @agungsugiarto, klik salah 1 angka untuk menampilkan detailnya, maka yang tampil hanya data kosong.
Contoh : 
<img width="529" alt="image" src="https://github.com/OpenSID/tracksid/assets/57283157/17927695-926c-4020-9b27-8312ef00564b">

<img width="541" alt="image" src="https://github.com/OpenSID/tracksid/assets/57283157/4f06846d-40e4-4e75-96a1-91112d391df9">

**Comment by agungsugiarto** [comment]
mas saya coba di https://pantau.opensid.my.id/laporan/kabupaten, tidak menemukan masalah?

**Comment by andifahruddinakas** [comment]
> mas saya coba di https://pantau.opensid.my.id/laporan/kabupaten, tidak menemukan masalah?

Misalnya klik 1 : 
<img width="545" alt="image" src="https://github.com/OpenSID/tracksid/assets/57283157/70e8a96a-7937-43ef-a8fa-cab608876c42">

Hasilnya : 
<img width="537" alt="image" src="https://github.com/OpenSID/tracksid/assets/57283157/9499649b-647b-4528-9705-a5c8d358a038">

Tadi hasilnya kosong, sekarang tampil semua. Dilihat dari urlnya : https://pantau.opensid.my.id/laporan/desa?status=1&kode_kabupaten=&kode_provinsi=

**Comment by agungsugiarto** [comment]
Masalah ini terkait database karena kode terkait seperti kode desa sampai ke kode provinsi kosong,

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/169
