### ISSUE TITLE
Penambahan data pelanggan_id pada response api/v1/wilayah untuk kebutuhan aplikasi layanan

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/tracksid#170]
Response yang dihasilkan dari url `api/v1/wilayah` sudah terdapat informasi desa_id,  namun belum diketahui penggunaan dari desa_id tersebut. Sedangkan pada aplikasi layanan ketika melakukan pendaftaran desa baru dibutuhkan list desa yang belum berlangganan. 
Solusi :
- [ ] Tambahkan field pelanggan_id sebagai penanda bahwa desa tersebut telah berlangganan
- [ ] Tambahkan filter untuk melakukan pencarian desa yang pelanggan_id bernilai null
- [ ] Tambahkan route untuk melakukan update data pelanggan_id agar layanan bisa memperbarui data desa

**Comment by FirlianiF** [comment]
Issue ini tidak jadi diterapkan.
