### ISSUE TITLE
Fitur menambah/ubah data wilayah kabupaten

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/tracksid#182]
Sudah diterapkan di tingkat desa, namun tingkat kabupaten belum disediakan.

<img width="680" alt="image" src="https://github.com/OpenSID/tracksid/assets/57283157/5604d295-bdbf-48fd-abcc-7525292854c2">

**Comment by eddieridwan** [comment]
Seperti dibahas, jangan. sediakan fitur untuk mengubah kabupaten/provinsi.
