### ISSUE TITLE
Fitur menambah/ubah data wilayah provinsi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/tracksid#183]
Sudah diterapkan di tingkat desa, namun tingkat provinsi belum disediakan.

<img width="680" alt="image" src="https://github.com/OpenSID/tracksid/assets/57283157/5604d295-bdbf-48fd-abcc-7525292854c2">

**Comment by eddieridwan** [comment]
Seperti sudah dibahas, jangan sediakan fitur untuk ubah data kabupaten/provinsi
