### ISSUE TITLE
Perbaikan data yang disimpan saat terima data dari OpenDK

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/tracksid#186]
Saat ini OpenDK mengirimkan 
`$data = [
            'url' => url('/'),
            'versi' => config('app.version'),
            'jumlah_desa' => DataDesa::count(),
            'desa' => json_encode(DataDesa::select(['desa_id', 'nama', 'sebutan_desa', 'path', 'website'])->get()),
            'jumlahdesa_sinkronisasi' => DataDesa::count(),
            'jumlah_penduduk' => Penduduk::where('status_dasar', 1)->count(),
            'jumlah_keluarga' => Keluarga::count(),
            'peta_wilayah'  => $this->umum->path ?? '[[[[]]]]',
            'batas_wilayah' => json_encode([
                'bts_wil_utara' => $this->umum->bts_wil_utara,
                'bts_wil_timur' => $this->umum->bts_wil_timur,
                'bts_wil_selatan' => $this->umum->bts_wil_selatan,
                'bts_wil_barat' => $this->umum->bts_wil_barat
            ]),
            'sebutan_wilayah' => $this->sebutan_wilayah,
            'alamat' => $this->profil->alamat,
            'jumlah_bantuan' => Program::count(),
            'kode_kecamatan' => $this->profil->kecamatan_id,
            'kode_kabupaten' => $this->profil->kabupaten_id,
            'kode_provinsi' => $this->profil->provinsi_id,
            'nama_kecamatan' => $this->profil->nama_kecamatan,
            'nama_kabupaten' => $this->profil->nama_kabupaten,
            'nama_provinsi' => $this->profil->nama_provinsi,
            'nama_camat' => $this->nama_camat
        ];`

Sedangkan di tracksid beberapa data belum disimpan di dalam tabel opendk
Solusi : 
- [ ] Simpan data batas_wilayah, jumlahdesa_sinkronisasi, alamat, jumlah_bantuan, lat, lng
- [ ] Untuk data lat dan lng perlu penambahan pada OpenDK agar peta bisa tampil dengan sempurna

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/189
