### ISSUE TITLE
Aplikasi mengalami internal error server dengan code 500 ketika gagal mengambil data versi terbaru dari github

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/tracksid#187]
Aplikasi gagal diakses dengan error code 500 dikarenakan gagal ambil data dari https://api.github.com/repos/OpenSID/rilis-premium/releases/latest

Solusi : 
- [ ] Gunakan cache untuk menyimpan data ketika akses ke url tersebut aman, gunakan nilai tersebut sebagai default sebelum request ulang ke url github sehingga diharapkan aplikasi bisa tetap berjalan meskipun gagal ambil data dari github

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/188
