### ISSUE TITLE
Desa yg sdh ada terdeteksi sebagai desa baru lagi

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#196]
Seharusnya desa yg sdh ada tidak terdeteksi sebagai desa baru lagi. Periksa apakah ini hanya masalah tampilan saja atau juga ada data desa duplikat.

<img width="1356" alt="image" src="https://github.com/OpenSID/tracksid/assets/249563/beb03c79-9515-4df4-a0d7-849fea6b3e46">

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/tracksid/assets/1853475/475f298a-34ee-446e-8d0e-3badd0c8f68d)
Dari data created_at record tersimpan dengan waktu yang sama, untuk menghidari hal seperti diatas akan ditambahkan constraint unique pada field kode_desa

**Comment by pandigresik** [comment]
Setelah dilakukan pengecekan ternyata banyak desa yang kembar berdasarkan hasil query 
`SELECT kode_desa FROM `desa` group by kode_desa having count(kode_desa) > 1`

ada sekitar 229 desa yang memiliki data kembar

1. 11.01.14.2002
2. 11.01.14.2005
3. 11.01.16.2005
4. 11.01.16.2007
5. 11.08.15.2020
6. 11.10.02.2012
7. 11.11.03.2052
8. 11.75.01.2012
9. 11.75.04.2003
10. 12.06.04.2023
11. 12.06.11.2007
12. 12.07.21.2006
13. 12.14.18.2005
14. 13.02.12.2003
15. 13.02.12.2005
16. 13.02.12.2007
17. 13.03.04.2007
18. 13.04.07.2004
19. 13.06.04.2002
20. 13.73.04.2010
21. 13.77.01.2018
22. 13.77.04.2004
23. 13.77.04.2015
24. 14.01.02.2032
25. 14.05.06.2008
26. 15.72.03.2002
27. 15.72.06.2005
28. 15.72.07.2005
29. 16.02.20.2005
30. 16.07.17.2005
31. 17.05.08.2008
32. 17.06.10.2007
33. 17.08.02.2004
34. 18.01.10.2001
35. 18.02.05.2001
36. 18.02.06.2005
37. 18.02.10.2013
38. 18.02.20.2001
39. 18.05.22.2009
40. 18.05.27.2009
41. 18.05.29.2004
42. 18.05.30.2003
43. 18.05.30.2004
44. 18.05.30.2005
45. 18.05.30.2006
46. 18.05.30.2008
47. 18.06.02.2027
48. 18.06.11.2015
49. 18.06.13.2007
50. 18.06.18.2016
51. 18.06.21.2010
52. 18.06.24.2010
53. 18.07.08.2003
54. 18.07.10.2007
55. 18.09.01.2008
56. 18.09.02.2014
57. 18.09.03.2002
58. 18.09.03.2006
59. 18.09.04.2001
60. 18.09.05.2012
61. 18.10.06.2001
62. 18.10.06.2003
63. 18.12.04.2013
64. 18.12.06.2008
65. 18.71.10.1008
66. 18.72.05.1001
67. 21.01.10.2002
68. 32.01.09.2009
69. 32.01.14.2005
70. 32.01.38.2005
71. 32.01.38.2006
72. 32.02.05.2013
73. 32.02.33.2004
74. 32.04.13.2001
75. 32.04.13.2013
76. 32.04.16.2009
77. 32.04.17.2004
78. 32.04.17.2008
79. 32.04.17.2010
80. 32.04.27.2006
81. 32.04.29.2010
82. 32.04.30.2005
83. 32.04.33.2005
84. 32.04.36.2002
85. 32.04.36.2008
86. 32.04.38.2005
87. 32.04.38.2008
88. 32.05.09.2009
89. 32.05.15.2001
90. 32.05.18.2004
91. 32.06.13.2004
92. 32.07.07.2001
93. 32.07.19.2009
94. 32.08.10.2007
95. 32.08.16.2006
96. 32.08.16.2013
97. 32.09.36.2003
98. 32.12.07.2006
99. 32.12.13.2006
100. 32.12.16.2002
101. 32.12.20.2012
102. 32.13.08.2011
103. 32.15.14.2006
104. 32.15.25.2009
105. 32.16.07.2004
106. 32.17.14.2009
107. 32.18.05.2011
108. 32.71.01.1012
109. 32.75.12.1001
110. 32.76.05.1001
111. 32.78.07.1005
112. 32.79.02.2005
113. 33.01.20.2005
114. 33.03.03.2010
115. 33.03.12.2005
116. 33.04.09.2011
117. 33.04.16.2008
118. 33.04.17.2003
119. 33.06.04.2012
120. 33.06.12.2025
121. 33.06.15.2004
122. 33.07.10.2008
123. 33.08.15.2010
124. 33.08.20.2015
125. 33.10.20.2002
126. 33.15.16.2002
127. 33.17.02.2011
128. 33.17.05.2007
129. 33.17.06.2014
130. 33.17.06.2019
131. 33.17.07.2003
132. 33.17.08.2020
133. 33.17.09.2014
134. 33.17.10.2007
135. 33.17.10.2009
136. 33.17.12.2009
137. 33.22.12.2009
138. 33.26.13.2011
139. 33.28.04.2012
140. 33.28.10.2005
141. 33.29.05.2011
142. 33.29.12.2011
143. 35.01.04.1013
144. 35.01.04.2023
145. 35.01.06.2006
146. 35.01.06.2015
147. 35.04.03.2013
148. 35.06.07.2007
149. 35.07.14.2002
150. 35.07.17.2015
151. 35.12.16.2006
152. 35.15.07.2020
153. 35.15.12.2010
154. 35.15.18.2009
155. 35.16.07.2012
156. 35.16.12.2005
157. 35.19.07.2012
158. 35.21.06.2013
159. 35.21.07.2008
160. 35.21.08.2012
161. 35.21.11.2009
162. 35.21.16.2003
163. 35.21.17.2007
164. 35.21.19.2002
165. 35.22.13.2019
166. 35.22.17.2006
167. 35.23.06.2001
168. 35.23.10.2005
169. 35.23.11.2007
170. 35.25.17.2013
171. 35.28.02.2010
172. 35.29.02.2001
173. 35.29.17.2008
174. 35.29.18.2007
175. 35.71.01.1011
176. 36.03.01.2013
177. 36.04.13.2007
178. 36.74.07.1004
179. 51.06.01.2005
180. 51.06.04.2027
181. 51.06.04.2040
182. 51.06.04.2041
183. 51.06.04.2042
184. 51.06.04.2044
185. 52.01.14.2005
186. 52.03.03.2012
187. 52.03.07.1010
188. 52.03.09.2024
189. 52.03.12.2002
190. 52.03.12.2004
191. 52.03.19.2010
192. 52.03.20.2014
193. 52.04.06.2002
194. 52.04.08.1001
195. 52.04.13.2004
196. 52.04.13.2013
197. 52.06.01.2010
198. 52.06.04.2004
199. 53.06.04.2005
200. 53.06.08.2030
201. 53.06.18.2012
202. 53.10.15.2010
203. 61.03.12.2004
204. 61.06.15.2010
205. 62.02.06.1007
206. 62.09.03.2031
207. 63.10.08.2009
208. 64.01.08.2006
209. 64.02.09.2008
210. 64.09.04.2002
211. 71.07.10.2007
212. 71.72.05.1002
213. 72.04.03.2011
214. 72.07.03.2008
215. 72.08.08.2002
216. 72.71.04.1002
217. 73.08.09.2010
218. 73.10.08.2006
219. 73.14.05.2007
220. 73.15.02.2006
221. 73.16.12.2004
222. 73.17.03.2017
223. 74.02.37.2005
224. 74.02.37.2006
225. 75.05.03.2009
226. 81.71.01.2005
227. 82.03.20.2005
228. 82.71.07.1001
229. 91.11.05.2011

Apakah akan kita bersihkan datanya agar tidak kembar, setelah itu baru bisa kita tambahkan constraint unique untuk kolom kode_desa

**Comment by pandigresik** [comment]
`select count(*) from desa where kode_desa = '52.01.14.2005'`
Satu desa dengan data kembar sebanyak 37 baris

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/197
