### ISSUE TITLE
Sesuaikan data yang dikirm melalui OpenSID untuk di tampung pada database trackSID 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/tracksid#200]
1. jika di lihat dari modul OpenSID ada kirim data ke sini : 
![image](https://github.com/OpenSID/tracksid/assets/59082428/bb29bd57-caf4-4941-b604-106e70f22559)

2. Lalu di TrackSID datanya tidak lengkap hanya ada ini:
![image](https://github.com/OpenSID/tracksid/assets/59082428/72011c9c-ab7a-45a1-927f-db34fa86bbc1)

Ubahannya perlu di sesuaikan agar trackSID dapat menampung data yang lain

**Comment by yogiperdana** [comment]
Duplikat issue https://github.com/OpenSID/tracksid/issues/146

**Comment by yogiperdana** [comment]
Issue tersebut sudah dikerjakan di tracksid namun terdapat penyesuaian data di di opensid https://github.com/OpenSID/OpenSID/issues/6859
