### ISSUE TITLE
Data pantau dari OpenSID tidak terkirim

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/tracksid#206]
Setelah rilis tgl 1, data pantau tidak terkirim / masuk ke server pantau. Pada log OpenSID terlihat error berikut : 
```
ERROR - 2023-09-05 11:22:44 --> GuzzleHttp\Exception\ClientException: Client error: `POST http://pantau.opensid.my.id/api/track/desa?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6bnVsbCwidGltZXN0YW1wIjoxNjAzNDY2MjM5fQ.HVCNnMLokF2tgHwjQhSIYo6-2GNXB4-Kf28FSIeXnZw` resulted in a `422 Unprocessable Entity` response:
{"message":"The given data was invalid.","errors":{"url":["Format url tidak valid."]}}
```

**Comment by yogiperdana** [comment]
Data tidak terkirim dikarenakan terdapat perubahan pengaturan daftar domain yang diabaikan yang saat ini ditambahkan melalui pengaturan aplikasi dan disimpan di cache. Karena merupakan fitur baru dan cachenya belum dibuat, maka cache harus dibuat terlebih dahulu.

Saat ini sudah berjalan dengan normal. Dengan demikian issue ini ditutup
