### ISSUE TITLE
Tambahkan Filter Pilihan Pengelompokan per.Wilayah di Dasbor Pantau OpenSID

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/tracksid#23]
Sekarang memang sudah tersedia filter pengelompokan wilayah pengguna opensid di dasbord pantau/tracksid, namun baru pilihan Kabupaten/Kota.

Yang ingin ditambahkan/Sediakan pengelompokan perwilayah saat melakukan filter wilayah pengguna opensid di Pantau :
1. Per Provinsi
2. Kabupaten/Kota
3. Kecamatan

Gunanya untuk mempermudah kita memantau penggunaan opensid di masing-masing wilayah dan dapat mengukur perkembangan/ pengguna opensid di seluruh wilayah indonesia.

FIleter yang tersedia saat ini : 
![fil](https://user-images.githubusercontent.com/32125282/111746569-cf6c1f00-88c0-11eb-8259-a3b6366baea1.png)

Yang di inginkan : 
![fileter](https://user-images.githubusercontent.com/32125282/111746956-4acdd080-88c1-11eb-9923-f947eb9ca78d.png)

**Comment by eddieridwan** [comment]
Duplikat https://github.com/OpenSID/tracksid/issues/53
