### ISSUE TITLE
Data desa dapat dipantau untuk wilayah tertentu saja

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/tracksid#53]
Jika akses dengan url tertentu, maka akan ditampilkan data berdasarkan kabupaten / provinsi yang bersangkutan pada semua menu dan halaman.

Fitur ini untuk digunakan oleh wilayah yg bekerjasama dengan OpenDesa untuk memantau penerapan OpenSID di wilayah ybs. Misalnya Prov NTB memerlukan fitur untuk bisa memantau secara khusus hanya desa di NTB saja. Contoh lain juga perlu bisa memantau penerapan OpenSID di Kab Sangihe yg akan menjadi pilot bagi suatu instansi pusat.

Jika memantau kabupaten tertentu, fitur tidak terkait, misalnya perbandingan antar kabupaten dsbnya tidak ditampilkan.

Perlu analisis lebih menyeluruh untuk issue ini supaya sesuai kebutuhan dan juga arsitektur teknis supaya tetap bisa mendukung fitur normal untuk keseluruhan wilayah.

**Comment by agungsugiarto** [comment]
- [ ] Scope hanya untuk data laporan
- [ ] Wilayah tertentu tidak perlu login
- [ ] Buatkan menu khusus
- [ ] TODO:

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/105
