### ISSUE TITLE
Bisa ambil data desa dari TrackSID menggunakan kode_desa

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#54]
Saat ini, di application/models/Wilayah_model_api.php->api_get_ambildesa($id_desa) perlu dipanggil menggunakan id_desa, sedangkan untuk mendukung Dashboard SaaS, OpenSID perlu bisa memanggil fungsi tersebut menggunakan kode_desa. Lihat issue https://github.com/OpenSID/OpenSID/issues/5205.

Ubah method itu supaya data desa bisa dicari menggunakan id_desa atau kode_desa.

**Comment by andifahruddinakas** [comment]
Sudah ada sebelumnya, bisa gunakan : 
`https://pantau.opensid.my.id/index.php/wilayah/kodedesa?token=isi_token&kode='isi_kode'`

**Comment by eddieridwan** [comment]
Issue ini ditutup, karena sudah tersedia.
