### ISSUE TITLE
Jumlah desa aktif dan desa baru dalam 7 hari terakhir salah

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#61]
Tidak mungkin ada ribuan desa baru dalam 7 hari terakhir. Jumlah desa aktif sebelumnya sekitar 7.000 desa. Sepertinya ada yg salah kalau sekarang hanya terlihat sekitar 5.000 desa aktif.

![image](https://user-images.githubusercontent.com/249563/170854838-82757ef9-35c0-40a0-a2cd-df643e006325.png)

**Comment by agungsugiarto** [comment]
Pak @eddieridwan dilihat dari query dan data di table desa seharusnya tidak ada masalah

```sql
SELECT 
  COUNT(*) AS AGGREGATE 
FROM 
  `desa` 
WHERE 
  (
    SELECT 
      if(
        versi_lokal IS NULL, 
        tgl_rekam_hosting, 
        if(
          versi_hosting IS NULL, 
          tgl_rekam_lokal, 
          LEAST(
            tgl_rekam_lokal, tgl_rekam_hosting
          )
        )
      ) AS tgl_rekam
  ) >= DATE(NOW()) - INTERVAL 7 DAY
```

<img width="886" alt="image" src="https://user-images.githubusercontent.com/10989147/170933396-2502ccc6-8985-4a1c-9d5e-4cf56ee90b7b.png">

**Comment by eddieridwan** [comment]
@agungsugiarto , jelas di pantau.opendesa.id bermasalah. Perlu dicari akar permasalahannya.
