### ISSUE TITLE
Perbaikan dashboard

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#63]
Dashboard perlu disesuaikan sebagai berikut:

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/249563/172046593-05f11b5c-25f1-4c3f-b32c-dd3bb1d12148.png">

**Comment by agungsugiarto** [comment]
Pak @eddieridwan untuk
- kabupaten pengguna premium
- kabupaten pengguna versi terbaru
apakah perhitungannya juga perlu disesuaikan?

**Comment by eddieridwan** [comment]
Ya, tentu saja. Statistik itu yg perlu ditampilkan. Dan jika di-klik, rincian desanya ditampilkan.

**Comment by andifahruddinakas** [comment]
> Ya, tentu saja. Statistik itu yg perlu ditampilkan. Dan jika di-klik, rincian desanya ditampilkan.

Untuk ini akan di buat di PR terpisah.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/85
