### ISSUE TITLE
Error bersihkan data akses

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#80]
Langkah:
1. login
2. klik Bersihkan Data Akses
3. error 500

![Image](https://user-images.githubusercontent.com/249563/179871690-0e88ad81-06a8-4428-8daf-7a978feeff6c.png)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui commit https://github.com/OpenSID/tracksid/commit/ab0faeeeacab20f21355c05bde0a6895d7437e36
