### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#81]
Langkah:
1. Klik login
2. isi credentials
3. login
4. error 404 (tetapi login berhasil; hanya redirect the route yg tidak ada)

![Image](https://user-images.githubusercontent.com/249563/179872032-4d59a121-2a4f-45d6-a893-9505783c7e04.png)

**Comment by andifahruddinakas** [comment]
Sudah di perbaiki lewat commit https://github.com/OpenSID/tracksid/commit/c9b437f5b14d23d150a8505ac35bdedb71ebb199
