### ISSUE TITLE
Perbaiki tampilan desa baru

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#93]
Perbaiki tampilan daftar desa baru, seperti terlihat di gambar berikut

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/249563/183012178-a4c5bcfa-a1af-4190-bbc7-17b3db26e1c9.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/96
