### ISSUE TITLE
Peta awal supaya otomatis menampilkan semua desa dalam window

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#94]
Saat ini ada desa terpotong jika layar tidak lebar penuh.

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/249563/183013107-2c61e61f-d56e-472e-96f6-6ff792b229ce.png">

**Comment by agungsugiarto** [comment]
Pak @eddieridwan jika di zoom out defaultnya adalah sebagai berikut
![Image](https://user-images.githubusercontent.com/10989147/183576381-43059f5f-d34f-442f-b23a-11228bd0561b.png),

Jika digeser ke kiri tanpa di zoom out maka provinsi aceh yang akan tertutup

**Comment by eddieridwan** [comment]
@agungsugiarto bisa lihat fitur leaflet untuk menampilkan semua marker dalam window. Contoh:
https://stackoverflow.com/questions/16845614/zoom-to-fit-all-markers-in-mapbox-or-leaflet

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/98
