### ISSUE TITLE
Perbaiki daftar versi OpenSID

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tracksid#95]
Perbaiki daftar versi OpenSID seperti di gambar berikut:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/249563/183015266-95b28588-58a2-404e-ae9c-b137c61d888f.png">

**Comment by eddieridwan** [comment]
Sekalian juga tambahkan filter semua/aktif:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/249563/183024496-7cb2c7bb-49b9-41ba-b7f5-3fa6902e534a.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/97
