### ISSUE TITLE
Jumlah desa aktif hanya offline tidak sesuai

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/tracksid#99]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/10989147/184061413-53ff2ade-38e9-4495-829c-694c0a69b160.png">

**Comment by agungsugiarto** [comment]
Pak @eddieridwan query untuk menghitung jumlah `Desa Aktif Hanya Offline` alias `desa_offline`, apakah yg dimaksud tidak perlu untuk membandingkan `x.tgl_akses_hosting` ?

```sql
select
    count(id) as desa_total,
    (
        select
            count(id)
        from
            desa as x
        where
            x.versi_lokal <> ''
            and greatest(
                coalesce(x.tgl_akses_lokal, 0),
                coalesce(x.tgl_akses_hosting, 0)
            ) >= now() - interval 7 day
    ) desa_offline,
    (
        select
            count(id)
        from
            desa as x
        where
            x.versi_hosting <> ''
            and greatest(
                coalesce(x.tgl_akses_lokal, 0),
                coalesce(x.tgl_akses_hosting, 0)
            ) >= now() - interval 7 day
    ) desa_online,
    count(distinct nama_kabupaten) as kabupaten_total,
    (
        select
            count(distinct x.nama_kabupaten)
        from
            desa as x
        where
            x.versi_lokal <> ''
    ) kabupaten_offline,
    (
        select
            count(distinct x.nama_kabupaten)
        from
            desa as x
        where
            x.versi_hosting <> ''
    ) kabupaten_online,
    (
        select
            count(id)
        from
            desa as x
        where
            x.jenis = 2
    ) bukan_desa,
    (
        select
            count(id)
        from
            desa as x
        where
            greatest(
                coalesce(x.tgl_akses_lokal, 0),
                coalesce(x.tgl_akses_hosting, 0)
            ) < now() - interval 4 month
    ) tidak_aktif,
    (
        select
            count(id)
        from
            desa as x
        where
            greatest(
                coalesce(x.tgl_akses_lokal, 0),
                coalesce(x.tgl_akses_hosting, 0)
            ) >= now() - interval 7 day
    ) aktif
from
    `desa`
```

**Comment by eddieridwan** [comment]
Perlu, karena judulnya Desa Aktif Hanya Offline. Yaitu yg aktif dalam 7 hari terakhir & desa offline & TIDAK desa online.

**Comment by agungsugiarto** [comment]
Kalau begitu query ini seharusnya sudah benar pak, karena yg dicari `versi_lokal` (offline)

> ```sql
>         select
>             count(id)
>         from
>             desa as x
>         where
>             x.versi_lokal <> ''
>             and greatest(
>                 coalesce(x.tgl_akses_lokal, 0),
>                 coalesce(x.tgl_akses_hosting, 0)
>             ) >= now() - interval 7 day
> ```

**Comment by eddieridwan** [comment]
> offline

Masih kurang. Syaratnya juga desa ybs TIDAK ONLINE.

**Comment by agungsugiarto** [comment]
> > offline
> 
> Masih kurang. Syaratnya juga desa ybs TIDAK ONLINE (`versi_hosting is null`). Ingat yg dicari HANYA offline, yaitu tidak ada webnya atau versi hostingnya.

`x.tgl_akses_hosting` (online) seharusnya tidak perlu dibandingkan dengan `x.tanggal_akses_lokal` (offline), query ini sudah memfilter desa yg offline pak

```sql
select
    count(id)
from
    desa as x
where
    x.versi_lokal <> ''
    and coalesce(x.tgl_akses_lokal, 0) >= now() - interval 7 day
```

**Comment by eddieridwan** [comment]
> > > offline
> > 
> > 
> > Masih kurang. Syaratnya juga desa ybs TIDAK ONLINE (`versi_hosting is null`). Ingat yg dicari HANYA offline, yaitu tidak ada webnya atau versi hostingnya.
> 
> `x.tgl_akses_hosting` (online) seharusnya tidak perlu dibandingkan dengan `x.tanggal_akses_lokal` (offline), query ini sudah memfilter desa yg offline pak
> 
> ```sql
> select
>     count(id)
> from
>     desa as x
> where
>     x.versi_lokal <> ''
>     and coalesce(x.tgl_akses_lokal, 0) >= now() - interval 7 day
> ```

Kalau hasilnya seperti kemarin, itu SALAH. Karena desa yg ditampilkan termasuk desa yg juga mempunyai website, yaitu tidak HANYA offline.

**Comment by eddieridwan** [comment]
Ingat suatu desa bisa mempunyai website (online) dan juga instalasi offline. Yg dicari adalah desa yg HANYA offline saja. Jadi jumlahnya akan sedikit.

**Comment by eddieridwan** [comment]
Coba gunakan:

```sql
select
    count(id)
from
    desa as x
where
    x.versi_lokal <> ''
    and x.versi_hosting is null
    and coalesce(x.tgl_akses_lokal, 0) >= now() - interval 7 day
```

**Comment by agungsugiarto** [comment]
> ```sql
> and x.versi_hosting is null
> ```

baik pak sudah dicoba

<img width="364" alt="image" src="https://user-images.githubusercontent.com/10989147/184282674-65e6f69c-3859-432d-bceb-bf6e4f3520e0.png">

**Comment by eddieridwan** [comment]
Ok. 
Tapi mengapa sepertinya konsep ini begitu sulit bagi anda untuk memahami? Seharusnya sederhana saja untuk dimengerti, seperti terlihat di venn diagram di bawah.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/249563/184284703-6aac36b6-9a2e-4648-88d5-e2ed3c251adb.png">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tracksid/pull/103
